# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-23 03:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default_category.jpg', upload_to='category_images')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default_thing.jpg', upload_to='thing_images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forge.Category')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default_tile.jpg', upload_to='tile_images')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default_world.jpg', upload_to='world_images')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='tile',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forge.World'),
        ),
        migrations.AddField(
            model_name='thing',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forge.World'),
        ),
        migrations.AddField(
            model_name='category',
            name='tile',
            field=models.ManyToManyField(blank=True, to='forge.Tile'),
        ),
        migrations.AddField(
            model_name='category',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forge.World'),
        ),
    ]
