# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-23 04:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forge', '0002_world_is_public'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('creator', 'world', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='thing',
            unique_together=set([('creator', 'world', 'name', 'category')]),
        ),
        migrations.AlterUniqueTogether(
            name='tile',
            unique_together=set([('creator', 'world', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='world',
            unique_together=set([('creator', 'name')]),
        ),
    ]
