# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-24 02:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0007_auto_20181223_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[^\\\\]+$', 'Names cannot contain slashes.')]),
        ),
        migrations.AlterField(
            model_name='thing',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[^\\\\]+$', 'Names cannot contain slashes.')]),
        ),
        migrations.AlterField(
            model_name='tile',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[^\\\\]+$', 'Names cannot contain slashes.')]),
        ),
        migrations.AlterField(
            model_name='world',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[^\\\\]+$', 'Names cannot contain slashes.')]),
        ),
    ]
