# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-24 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import forge.models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0008_auto_20181223_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thing',
            old_name='tile',
            new_name='tiles',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_credit',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, validators=[forge.models.validate_name]),
        ),
        migrations.AlterField(
            model_name='thing',
            name='name',
            field=models.CharField(max_length=100, validators=[forge.models.validate_name]),
        ),
        migrations.AlterField(
            model_name='tile',
            name='name',
            field=models.CharField(max_length=100, validators=[forge.models.validate_name]),
        ),
        migrations.AlterField(
            model_name='world',
            name='name',
            field=models.CharField(max_length=100, validators=[forge.models.validate_name]),
        ),
    ]
