# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-25 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0009_auto_20181223_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='image_credit',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
