# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-26 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0011_auto_20181225_2319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('str_name',), 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='tile',
            options={'ordering': ('str_name',)},
        ),
        migrations.AlterModelOptions(
            name='world',
            options={'ordering': ('str_name',)},
        ),
        migrations.AddField(
            model_name='category',
            name='str_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tile',
            name='str_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='world',
            name='str_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
