# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-27 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0013_auto_20181226_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='image_thumb',
            field=models.ImageField(default='default_world_thumb.jpg', upload_to='world_images/thumbs'),
        ),
    ]
