# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-27 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0014_auto_20181226_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='image_thumb',
            field=models.ImageField(default='default_thing_thumb.jpg', upload_to='thing_images/thumbs'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='image_thumb',
            field=models.ImageField(default='default_tile_thumb.jpg', upload_to='tile_images/thumbs'),
        ),
    ]
