# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-28 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0015_auto_20181226_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='horizontal_position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tile',
            name='vertical_position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
