# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-01 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0016_auto_20181228_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='image_thumb',
            field=models.ImageField(default='/static/forge/default_thing_thumb.jpg', upload_to='thing_images/thumbs'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='image_thumb',
            field=models.ImageField(default='/static/forge/default_tile_thumb.jpg', upload_to='tile_images/thumbs'),
        ),
        migrations.AlterField(
            model_name='world',
            name='image_thumb',
            field=models.ImageField(default='/static/forge/default_world_thumb.jpg', upload_to='world_images/thumbs'),
        ),
    ]
