# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-01 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0019_auto_20190101_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='image_thumb',
            field=models.ImageField(default='../forge/static/forge/default_thing.jpg', upload_to='thing_images/thumbs'),
        ),
    ]
