# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-01 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0020_auto_20190101_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='image',
            field=models.ImageField(default='../forge/static/forge/default_thing.jpg', upload_to='thing_images'),
        ),
    ]
