# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-01 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0021_auto_20190101_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='image',
            field=models.ImageField(blank=True, upload_to='thing_images'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='image_thumb',
            field=models.ImageField(blank=True, upload_to='thing_images/thumbs'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='image',
            field=models.ImageField(blank=True, upload_to='tile_images'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='image_thumb',
            field=models.ImageField(blank=True, upload_to='tile_images/thumbs'),
        ),
        migrations.AlterField(
            model_name='world',
            name='image',
            field=models.ImageField(blank=True, upload_to='world_images'),
        ),
        migrations.AlterField(
            model_name='world',
            name='image_thumb',
            field=models.ImageField(blank=True, upload_to='world_images/thumbs'),
        ),
    ]
