# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-28 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181222_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_thumb',
            field=models.ImageField(default='default_profile_thumb.jpg', upload_to='profile_pics/thumbs'),
        ),
    ]
