# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-31 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_image_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_tier',
            field=models.IntegerField(default=1),
        ),
    ]
